#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Concatenate stream files
#
# Copyright © 2017-2020 Deutsches Elektronen-Synchrotron DESY,
#                       a research centre of the Helmholtz Association.
#
# Author:
#    2024 Ana Carolina Rodrigues
#

import sys
import numpy as np
import h5py
from os.path import basename, splitext
import glob

streams = sorted(glob.glob(sys.argv[1]+"*"))

output = open(sys.argv[2],"w")
print(streams)

for path in streams:
    print(path)
    stream = open(path, 'r')
    reading_geometry = False
    reading_chunks = False
    reading_peaks = False
    max_fs = -100500
    max_ss = -100500

    for line in stream:
        output.write(line)
    stream.close()
    output.write("\n")
output.close()